spring:
  mail:
    host: mail.projectain.com
    port: 587
    from: no-reply@projectain.com
  datasource:
    url:  jdbc:mariadb://projectain.com/srv53677_app
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect

enable-email-confirmation: true

jwt:
  expirationTime: 3600000

confirmation:
  frontend:
    url: https://projectain-frontend.herokuapp.com/confirm/