frontend.url: http://localhost:4200

reset:
  password:
    frontend:
      url: ${frontend.url}/reset/password/

spring:
  datasource:
    password: root
    username: root
    url: jdbc:postgresql://localhost:5432/task_management
  mail:
    host: smtp.gmail.com
    port: 587
    username: task.management.mw.inzynierka@gmail.com
    password: jbrbzwlomlakvtzc
    from: task.management.mw.inzynierka@gmail.com

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

confirmation:
  frontend:
    url: http://localhost:4200/confirm/

enable-email-confirmation: true

jwt:
  expirationTime: 3600000
  secret: secret
server:
  port: 8080