spring:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  mail:
    host: mail.projectain.com
    port: 587

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

confirmation:
  frontend:
    url: http://localhost:4200/confirm/

jwt:
  expirationTime: 3600000
  secret: secret
server:
  port: 8080